version: '3.4'

services:
  eventgridemulator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - "~/.workleap/workleap-dev-certificate.crt:/etc/ssl/certs/localhost.crt"
      - "~/.workleap/workleap-dev-certificate.key:/etc/ssl/certs/localhost.key"