name: Publish

on:
  push:
    tags: ["*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2
        with:
          username: ${{ secrets.WORKLEAP_DOCKERHUB_USERNAME }}
          password: ${{ secrets.WORKLEAP_DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 #v4
        with:
          images: workleap/eventgridemulator

      - name: Docker build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 #v4
        with:
          context: ./src
          file: ./src/EventGridEmulator/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}