name: Publish

on:
  push:
    tags: ["*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - run: ./Build.ps1
        shell: pwsh

      - name: Docker login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ secrets.WORKLEAP_DOCKERHUB_USERNAME }}
          password: ${{ secrets.WORKLEAP_DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: workleap/eventgridemulator

      - name: Docker build and push
        uses: docker/build-push-action@16ebe778df0e7752d2cfcbd924afdbbd89c1a755 # v6
        with:
          context: ./src
          file: ./src/EventGridEmulator/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  linearb:
    needs: [publish]
    uses: gsoft-inc/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: "release"
    secrets: inherit
